# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TextureExam (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'AsyncDisplayKit'

  # Pods for TextureExam (iOS)

end

target 'TextureExam (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TextureExam (macOS)

end
